In [130]:
import os 
from pathlib import Path
import pandas as pd

In [131]:
Path(os.getcwd()).parent

WindowsPath('c:/Full_stack/Porfolio/France_energie_intelligence/energy-france-analysis')

In [132]:
Path_data = Path(Path(os.getcwd()).parent)/"data/raw/"
Path_data

WindowsPath('c:/Full_stack/Porfolio/France_energie_intelligence/energy-france-analysis/data/raw')

In [133]:
from pathlib import Path

import pandas as pd


file_path = Path(
    "../data/raw/eCO2mix_RTE_Annuel-Definitif_2024.xls"
)

# Lecture de la ligne d'en-tête pour récupérer les 40 noms officiels
with open(file_path, "r", encoding="latin-1") as file:
    column_names = file.readline().rstrip("\r\n").split("\t")

print(f"Nombre de colonnes attendues : {len(column_names)}")

df_2024 = pd.read_csv(
    file_path,
    sep="\t",
    encoding="latin-1",
    header=0,
    names=column_names,
    usecols=range(len(column_names)),
    index_col=False,
    low_memory=False,
)

Nombre de colonnes attendues : 40

In [134]:
df_2024.shape

(35137, 40)

In [135]:
df = df_2024.copy()

In [136]:
pd.set_option('display.max_columns', 40)
pd.set_option('display.max_rows', 600)

In [137]:
df.tail()

,Périmètre,Nature,Date,Heures,Consommation,Prévision J-1,Prévision J,Fioul,Charbon,Gaz,Nucléaire,Eolien,Solaire,Hydraulique,Pompage,Bioénergies,Ech. physiques,Taux de Co2,Ech. comm. Angleterre,Ech. comm. Espagne,Ech. comm. Italie,Ech. comm. Suisse,Ech. comm. Allemagne-Belgique,Fioul - TAC,Fioul - Cogén.,Fioul - Autres,Gaz - TAC,Gaz - Cogén.,Gaz - CCG,Gaz - Autres,Hydraulique - Fil de l?eau + éclusée,Hydraulique - Lacs,Hydraulique - STEP turbinage,Bioénergies - Déchets,Bioénergies - Biomasse,Bioénergies - Biogaz,Stockage batterie,Déstockage batterie,Eolien terrestre,Eolien offshore
35132,France,Données définitives,2024-12-31,23:00,65437.0,64200.0,64300.0,92.0,17.0,2130.0,50923.0,10390.0,0.0,5377.0,-2014.0,1278.0,-2656.0,19.0,3009.0,-2900.0,-3589.0,-3200.0,3805.0,14.0,57.0,21.0,101.0,651.0,622.0,756.0,4503.0,718.0,155.0,548.0,386.0,344.0,0.0,0.0,9111.0,1279.0
35133,France,Données définitives,2024-12-31,23:15,NaN,64500.0,64550.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3009.0,-2900.0,-3589.0,-3200.0,3805.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35134,France,Données définitives,2024-12-31,23:30,65159.0,64800.0,64800.0,92.0,16.0,2121.0,51095.0,10520.0,0.0,5429.0,-1954.0,1288.0,-3358.0,19.0,3009.0,-2900.0,-3589.0,-3200.0,3805.0,14.0,57.0,21.0,101.0,651.0,613.0,756.0,4619.0,585.0,225.0,554.0,389.0,345.0,0.0,0.0,9183.0,1337.0
35135,France,Données définitives,2024-12-31,23:45,NaN,64400.0,64500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3009.0,-2900.0,-3589.0,-3200.0,3805.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35136,RTE ne pourra être tenu responsable de l'usage...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [138]:
df.describe(include='all')

,Périmètre,Nature,Date,Heures,Consommation,Prévision J-1,Prévision J,Fioul,Charbon,Gaz,Nucléaire,Eolien,Solaire,Hydraulique,Pompage,Bioénergies,Ech. physiques,Taux de Co2,Ech. comm. Angleterre,Ech. comm. Espagne,Ech. comm. Italie,Ech. comm. Suisse,Ech. comm. Allemagne-Belgique,Fioul - TAC,Fioul - Cogén.,Fioul - Autres,Gaz - TAC,Gaz - Cogén.,Gaz - CCG,Gaz - Autres,Hydraulique - Fil de l?eau + éclusée,Hydraulique - Lacs,Hydraulique - STEP turbinage,Bioénergies - Déchets,Bioénergies - Biomasse,Bioénergies - Biogaz,Stockage batterie,Déstockage batterie,Eolien terrestre,Eolien offshore
count,35137,35136,35136,35136,17568.000000,35136.000000,35136.000000,17568.000000,17568.000000,17568.000000,17568.000000,17568.000000,17568.000000,17568.000000,17568.000000,17568.000000,17568.000000,17568.000000,26592.000000,26592.000000,26592.00000,26592.000000,26592.000000,17568.000000,17568.000000,17568.000000,17568.000000,17568.000000,17568.000000,17568.000000,17568.000000,17568.000000,17568.000000,17568.000000,17568.000000,17568.000000,17568.0,17568.0,17568.000000,17568.000000
unique,2,1,366,96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,France,Données définitives,2024-01-01,00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,35136,35136,96,366,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,50100.899932,48954.843181,48933.446465,114.317338,82.528347,1983.560166,41176.831000,5330.410121,2787.203609,8522.093124,-839.412284,1212.144012,-10197.047359,18.990893,-2165.865824,-596.707694,-2542.82773,-1840.535575,-3105.806069,36.242543,66.789447,11.595287,61.276810,562.924066,949.298042,410.452015,5451.372837,2322.118112,748.607127,497.302596,374.613103,340.229053,0.0,0.0,4877.135644,453.621869
std,NaN,NaN,NaN,NaN,9992.471704,9867.433630,9787.287334,124.395783,170.247947,2101.735439,5659.430678,4276.164150,3949.140269,2723.374828,951.684647,63.545634,3821.345610,12.138014,1435.944971,1905.023013,917.84457,1192.298682,3176.865354,121.659011,7.721221,11.468149,79.179458,358.433379,1491.805480,442.513140,1218.571181,1183.129638,856.887082,40.002332,32.003623,10.426528,0.0,0.0,3996.798629,372.392389
min,NaN,NaN,NaN,NaN,30348.000000,29400.000000,29300.000000,56.000000,0.000000,260.000000,20559.000000,60.000000,0.000000,2366.000000,-3731.000000,995.000000,-20083.000000,7.000000,-4028.000000,-3607.000000,-4947.00000,-3210.000000,-9258.000000,0.000000,43.000000,3.000000,0.000000,190.000000,0.000000,19.000000,2100.000000,171.000000,3.000000,328.000000,212.000000,301.000000,0.0,0.0,85.000000,0.000000
25%,NaN,NaN,NaN,NaN,42930.750000,41800.000000,41900.000000,80.000000,12.000000,453.000000,38209.000000,2053.000000,0.000000,6638.750000,-1564.000000,1173.000000,-12719.000000,9.000000,-3104.000000,-2233.250000,-3138.00000,-2385.000000,-5226.000000,8.000000,62.000000,4.000000,4.000000,279.000000,104.000000,42.000000,4671.750000,1440.000000,79.750000,469.000000,360.000000,333.000000,0.0,0.0,1844.750000,145.000000
50%,NaN,NaN,NaN,NaN,48773.000000,47600.000000,47500.000000,88.000000,17.000000,984.000000,40889.000000,4027.000000,72.500000,8274.000000,-387.000000,1220.000000,-10720.500000,15.000000,-2448.500000,-1300.000000,-2535.00000,-2227.000000,-3804.000000,13.000000,65.000000,6.000000,38.000000,334.000000,192.000000,63.000000,5637.000000,2138.500000,369.000000,499.000000,381.000000,341.000000,0.0,0.0,3614.000000,358.000000
75%,NaN,NaN,NaN,NaN,56589.000000,55200.000000,55300.000000,99.000000,20.000000,2588.250000,44799.750000,7598.000000,5184.000000,10215.000000,-26.000000,1259.000000,-8299.750000,24.000000,-1161.750000,1100.000000,-2000.00000,-1515.000000,-1992.000000,14.000000,71.000000,19.000000,102.000000,822.000000,956.000000,860.000000,6305.000000,3015.000000,1233.000000,526.000000,397.000000,348.000000,0.0,0.0,6902.250000,698.000000
max,NaN,NaN,NaN,NaN,85370.000000,85000.000000,84400.000000,1542.000000,1093.000000,9343.000000,53319.000000,19744.000000,16658.000000,17711.000000,-3.000000,1383.000000,7777.000000,69.000000,3905.000000,3648.000000,1321.00000,1330.000000,9040.000000,1227.000000,92.000000,325.000000,732.000000,1735.000000,6425.000000,1300.000000,8430.000000,6852.000000,4205.000000,617.000000,440.000000,372.000000,0.0,0.0,18499.000000,1455.000000

In [139]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 35137 entries, 0 to 35136
Data columns (total 40 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Périmètre                             35137 non-null  str
 1   Nature                                35136 non-null  str
 2   Date                                  35136 non-null  str
 3   Heures                                35136 non-null  str
 4   Consommation                          17568 non-null  float64
 5   Prévision J-1                         35136 non-null  float64
 6   Prévision J                           35136 non-null  float64
 7   Fioul                                 17568 non-null  float64
 8   Charbon                               17568 non-null  float64
 9   Gaz                                   17568 non-null  float64
 10  Nucléaire                             17568 non-null  float64
 11  Eolien                                17568 non-null  float64
 12  Solaire                               17568 non-null  float64
 13  Hydraulique                           17568 non-null  float64
 14  Pompage                               17568 non-null  float64
 15  Bioénergies                           17568 non-null  float64
 16  Ech. physiques                        17568 non-null  float64
 17  Taux de Co2                           17568 non-null  float64
 18  Ech. comm. Angleterre                 26592 non-null  float64
 19  Ech. comm. Espagne                    26592 non-null  float64
 20  Ech. comm. Italie                     26592 non-null  float64
 21  Ech. comm. Suisse                     26592 non-null  float64
 22  Ech. comm. Allemagne-Belgique         26592 non-null  float64
 23  Fioul - TAC                           17568 non-null  float64
 24  Fioul - Cogén.                        17568 non-null  float64
 25  Fioul - Autres                        17568 non-null  float64
 26  Gaz - TAC                             17568 non-null  float64
 27  Gaz - Cogén.                          17568 non-null  float64
 28  Gaz - CCG                             17568 non-null  float64
 29  Gaz - Autres                          17568 non-null  float64
 30  Hydraulique - Fil de l?eau + éclusée  17568 non-null  float64
 31  Hydraulique - Lacs                    17568 non-null  float64
 32  Hydraulique - STEP turbinage          17568 non-null  float64
 33  Bioénergies - Déchets                 17568 non-null  float64
 34  Bioénergies - Biomasse                17568 non-null  float64
 35  Bioénergies - Biogaz                  17568 non-null  float64
 36   Stockage batterie                    17568 non-null  float64
 37  Déstockage batterie                   17568 non-null  float64
 38  Eolien terrestre                      17568 non-null  float64
 39  Eolien offshore                       17568 non-null  float64
dtypes: float64(36), str(4)
memory usage: 12.1 MB

In [140]:
df.loc[:,'Date'].unique()

<ArrowStringArray>
['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04', '2024-01-05',
 '2024-01-06', '2024-01-07', '2024-01-08', '2024-01-09', '2024-01-10',
 ...
 '2024-12-23', '2024-12-24', '2024-12-25', '2024-12-26', '2024-12-27',
 '2024-12-28', '2024-12-29', '2024-12-30', '2024-12-31',          nan]
Length: 367, dtype: str

### Mise en place du dictionnaire

####

In [141]:
df.head(5)

,Périmètre,Nature,Date,Heures,Consommation,Prévision J-1,Prévision J,Fioul,Charbon,Gaz,Nucléaire,Eolien,Solaire,Hydraulique,Pompage,Bioénergies,Ech. physiques,Taux de Co2,Ech. comm. Angleterre,Ech. comm. Espagne,Ech. comm. Italie,Ech. comm. Suisse,Ech. comm. Allemagne-Belgique,Fioul - TAC,Fioul - Cogén.,Fioul - Autres,Gaz - TAC,Gaz - Cogén.,Gaz - CCG,Gaz - Autres,Hydraulique - Fil de l?eau + éclusée,Hydraulique - Lacs,Hydraulique - STEP turbinage,Bioénergies - Déchets,Bioénergies - Biomasse,Bioénergies - Biogaz,Stockage batterie,Déstockage batterie,Eolien terrestre,Eolien offshore
0,France,Données définitives,2024-01-01,00:00,55239.0,55000.0,54200.0,96.0,18.0,1975.0,39886.0,15557.0,0.0,6671.0,-2274.0,1211.0,-7824.0,20.0,-1447.0,-2636.0,-2235.0,-2214.0,2360.0,14.0,63.0,18.0,88.0,761.0,201.0,926.0,5001.0,1553.0,117.0,510.0,354.0,347.0,0.0,0.0,14976.0,581.0
1,France,Données définitives,2024-01-01,00:15,NaN,54300.0,53400.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,France,Données définitives,2024-01-01,00:30,55167.0,53600.0,52600.0,98.0,17.0,1926.0,38086.0,15467.0,0.0,6533.0,-2174.0,1217.0,-5890.0,20.0,-1447.0,-2636.0,-2235.0,-2214.0,2336.0,14.0,64.0,19.0,88.0,747.0,147.0,943.0,4928.0,1599.0,6.0,501.0,369.0,347.0,0.0,0.0,14888.0,579.0
3,France,Données définitives,2024-01-01,00:45,NaN,53200.0,51950.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,France,Données définitives,2024-01-01,01:00,53183.0,52800.0,51300.0,96.0,17.0,1987.0,37215.0,15411.0,0.0,6208.0,-2202.0,1225.0,-6659.0,21.0,-1431.0,-2636.0,-2102.0,-2280.0,1573.0,14.0,63.0,19.0,91.0,752.0,196.0,948.0,4909.0,1293.0,6.0,506.0,373.0,347.0,0.0,0.0,14830.0,581.0

In [142]:
df.columns.tolist()

['Périmètre',
 'Nature',
 'Date',
 'Heures',
 'Consommation',
 'Prévision J-1',
 'Prévision J',
 'Fioul',
 'Charbon',
 'Gaz',
 'Nucléaire',
 'Eolien',
 'Solaire',
 'Hydraulique',
 'Pompage',
 'Bioénergies',
 'Ech. physiques',
 'Taux de Co2',
 'Ech. comm. Angleterre',
 'Ech. comm. Espagne',
 'Ech. comm. Italie',
 'Ech. comm. Suisse',
 'Ech. comm. Allemagne-Belgique',
 'Fioul - TAC',
 'Fioul - Cogén.',
 'Fioul - Autres',
 'Gaz - TAC',
 'Gaz - Cogén.',
 'Gaz - CCG',
 'Gaz - Autres',
 'Hydraulique - Fil de l?eau + éclusée',
 'Hydraulique - Lacs',
 'Hydraulique - STEP turbinage',
 'Bioénergies - Déchets',
 'Bioénergies - Biomasse',
 'Bioénergies - Biogaz',
 ' Stockage batterie',
 'Déstockage batterie',
 'Eolien terrestre',
 'Eolien offshore']

In [143]:
df['Périmètre']

0                                                   France
1                                                   France
2                                                   France
3                                                   France
4                                                   France
                               ...
35132                                               France
35133                                               France
35134                                               France
35135                                               France
35136    RTE ne pourra être tenu responsable de l'usage...
Name: Périmètre, Length: 35137, dtype: str

In [144]:
df['Périmètre']

0                                                   France
1                                                   France
2                                                   France
3                                                   France
4                                                   France
                               ...
35132                                               France
35133                                               France
35134                                               France
35135                                               France
35136    RTE ne pourra être tenu responsable de l'usage...
Name: Périmètre, Length: 35137, dtype: str

In [145]:
df.shape

(35137, 40)

In [146]:
df['Nature']

0        Données définitives
1        Données définitives
2        Données définitives
3        Données définitives
4        Données définitives
                ...
35132    Données définitives
35133    Données définitives
35134    Données définitives
35135    Données définitives
35136                    NaN
Name: Nature, Length: 35137, dtype: str

In [147]:
df.head(5)

,Périmètre,Nature,Date,Heures,Consommation,Prévision J-1,Prévision J,Fioul,Charbon,Gaz,Nucléaire,Eolien,Solaire,Hydraulique,Pompage,Bioénergies,Ech. physiques,Taux de Co2,Ech. comm. Angleterre,Ech. comm. Espagne,Ech. comm. Italie,Ech. comm. Suisse,Ech. comm. Allemagne-Belgique,Fioul - TAC,Fioul - Cogén.,Fioul - Autres,Gaz - TAC,Gaz - Cogén.,Gaz - CCG,Gaz - Autres,Hydraulique - Fil de l?eau + éclusée,Hydraulique - Lacs,Hydraulique - STEP turbinage,Bioénergies - Déchets,Bioénergies - Biomasse,Bioénergies - Biogaz,Stockage batterie,Déstockage batterie,Eolien terrestre,Eolien offshore
0,France,Données définitives,2024-01-01,00:00,55239.0,55000.0,54200.0,96.0,18.0,1975.0,39886.0,15557.0,0.0,6671.0,-2274.0,1211.0,-7824.0,20.0,-1447.0,-2636.0,-2235.0,-2214.0,2360.0,14.0,63.0,18.0,88.0,761.0,201.0,926.0,5001.0,1553.0,117.0,510.0,354.0,347.0,0.0,0.0,14976.0,581.0
1,France,Données définitives,2024-01-01,00:15,NaN,54300.0,53400.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,France,Données définitives,2024-01-01,00:30,55167.0,53600.0,52600.0,98.0,17.0,1926.0,38086.0,15467.0,0.0,6533.0,-2174.0,1217.0,-5890.0,20.0,-1447.0,-2636.0,-2235.0,-2214.0,2336.0,14.0,64.0,19.0,88.0,747.0,147.0,943.0,4928.0,1599.0,6.0,501.0,369.0,347.0,0.0,0.0,14888.0,579.0
3,France,Données définitives,2024-01-01,00:45,NaN,53200.0,51950.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,France,Données définitives,2024-01-01,01:00,53183.0,52800.0,51300.0,96.0,17.0,1987.0,37215.0,15411.0,0.0,6208.0,-2202.0,1225.0,-6659.0,21.0,-1431.0,-2636.0,-2102.0,-2280.0,1573.0,14.0,63.0,19.0,91.0,752.0,196.0,948.0,4909.0,1293.0,6.0,506.0,373.0,347.0,0.0,0.0,14830.0,581.0

In [148]:
df.dtypes

Périmètre                                   str
Nature                                      str
Date                                        str
Heures                                      str
Consommation                            float64
Prévision J-1                           float64
Prévision J                             float64
Fioul                                   float64
Charbon                                 float64
Gaz                                     float64
Nucléaire                               float64
Eolien                                  float64
Solaire                                 float64
Hydraulique                             float64
Pompage                                 float64
Bioénergies                             float64
Ech. physiques                          float64
Taux de Co2                             float64
Ech. comm. Angleterre                   float64
Ech. comm. Espagne                      float64
Ech. comm. Italie                       float64
Ech. comm. Suisse                       float64
Ech. comm. Allemagne-Belgique           float64
Fioul - TAC                             float64
Fioul - Cogén.                          float64
Fioul - Autres                          float64
Gaz - TAC                               float64
Gaz - Cogén.                            float64
Gaz - CCG                               float64
Gaz - Autres                            float64
Hydraulique - Fil de l?eau + éclusée    float64
Hydraulique - Lacs                      float64
Hydraulique - STEP turbinage            float64
Bioénergies - Déchets                   float64
Bioénergies - Biomasse                  float64
Bioénergies - Biogaz                    float64
 Stockage batterie                      float64
Déstockage batterie                     float64
Eolien terrestre                        float64
Eolien offshore                         float64
dtype: object

In [149]:
df

,Périmètre,Nature,Date,Heures,Consommation,Prévision J-1,Prévision J,Fioul,Charbon,Gaz,Nucléaire,Eolien,Solaire,Hydraulique,Pompage,Bioénergies,Ech. physiques,Taux de Co2,Ech. comm. Angleterre,Ech. comm. Espagne,Ech. comm. Italie,Ech. comm. Suisse,Ech. comm. Allemagne-Belgique,Fioul - TAC,Fioul - Cogén.,Fioul - Autres,Gaz - TAC,Gaz - Cogén.,Gaz - CCG,Gaz - Autres,Hydraulique - Fil de l?eau + éclusée,Hydraulique - Lacs,Hydraulique - STEP turbinage,Bioénergies - Déchets,Bioénergies - Biomasse,Bioénergies - Biogaz,Stockage batterie,Déstockage batterie,Eolien terrestre,Eolien offshore
0,France,Données définitives,2024-01-01,00:00,55239.0,55000.0,54200.0,96.0,18.0,1975.0,39886.0,15557.0,0.0,6671.0,-2274.0,1211.0,-7824.0,20.0,-1447.0,-2636.0,-2235.0,-2214.0,2360.0,14.0,63.0,18.0,88.0,761.0,201.0,926.0,5001.0,1553.0,117.0,510.0,354.0,347.0,0.0,0.0,14976.0,581.0
1,France,Données définitives,2024-01-01,00:15,NaN,54300.0,53400.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,France,Données définitives,2024-01-01,00:30,55167.0,53600.0,52600.0,98.0,17.0,1926.0,38086.0,15467.0,0.0,6533.0,-2174.0,1217.0,-5890.0,20.0,-1447.0,-2636.0,-2235.0,-2214.0,2336.0,14.0,64.0,19.0,88.0,747.0,147.0,943.0,4928.0,1599.0,6.0,501.0,369.0,347.0,0.0,0.0,14888.0,579.0
3,France,Données définitives,2024-01-01,00:45,NaN,53200.0,51950.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,France,Données définitives,2024-01-01,01:00,53183.0,52800.0,51300.0,96.0,17.0,1987.0,37215.0,15411.0,0.0,6208.0,-2202.0,1225.0,-6659.0,21.0,-1431.0,-2636.0,-2102.0,-2280.0,1573.0,14.0,63.0,19.0,91.0,752.0,196.0,948.0,4909.0,1293.0,6.0,506.0,373.0,347.0,0.0,0.0,14830.0,581.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35132,France,Données définitives,2024-12-31,23:00,65437.0,64200.0,64300.0,92.0,17.0,2130.0,50923.0,10390.0,0.0,5377.0,-2014.0,1278.0,-2656.0,19.0,3009.0,-2900.0,-3589.0,-3200.0,3805.0,14.0,57.0,21.0,101.0,651.0,622.0,756.0,4503.0,718.0,155.0,548.0,386.0,344.0,0.0,0.0,9111.0,1279.0
35133,France,Données définitives,2024-12-31,23:15,NaN,64500.0,64550.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3009.0,-2900.0,-3589.0,-3200.0,3805.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35134,France,Données définitives,2024-12-31,23:30,65159.0,64800.0,64800.0,92.0,16.0,2121.0,51095.0,10520.0,0.0,5429.0,-1954.0,1288.0,-3358.0,19.0,3009.0,-2900.0,-3589.0,-3200.0,3805.0,14.0,57.0,21.0,101.0,651.0,613.0,756.0,4619.0,585.0,225.0,554.0,389.0,345.0,0.0,0.0,9183.0,1337.0
35135,France,Données définitives,2024-12-31,23:45,NaN,64400.0,64500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3009.0,-2900.0,-3589.0,-3200.0,3805.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35136,RTE ne pourra être tenu responsable de l'usage...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [168]:
print(df_2024['Consommation'].isna().sum()/len(df_2024)*100)
print(df_2024['Prévision J-1'].isna().sum()/len(df_2024)*100)
print(df_2024['Prévision J'].isna().sum()/len(df_2024)*100)

50.00142300139454
0.002846002789082733
0.002846002789082733

In [173]:
(
df_2024.loc[df_2024['Consommation'].notnull() , "Heures"]
.value_counts()
.sort_index()
)

Heures
00:00    366
00:30    366
01:00    366
01:30    366
02:00    366
02:30    366
03:00    366
03:30    366
04:00    366
04:30    366
05:00    366
05:30    366
06:00    366
06:30    366
07:00    366
07:30    366
08:00    366
08:30    366
09:00    366
09:30    366
10:00    366
10:30    366
11:00    366
11:30    366
12:00    366
12:30    366
13:00    366
13:30    366
14:00    366
14:30    366
15:00    366
15:30    366
16:00    366
16:30    366
17:00    366
17:30    366
18:00    366
18:30    366
19:00    366
19:30    366
20:00    366
20:30    366
21:00    366
21:30    366
22:00    366
22:30    366
23:00    366
23:30    366
Name: count, dtype: int64

In [180]:
df['Consommation']

0        55239.0
1            NaN
2        55167.0
3            NaN
4        53183.0
          ...
35132    65437.0
35133        NaN
35134    65159.0
35135        NaN
35136        NaN
Name: Consommation, Length: 35137, dtype: float64

In [182]:
df

,Périmètre,Nature,Date,Heures,Consommation,Prévision J-1,Prévision J,Fioul,Charbon,Gaz,Nucléaire,Eolien,Solaire,Hydraulique,Pompage,Bioénergies,Ech. physiques,Taux de Co2,Ech. comm. Angleterre,Ech. comm. Espagne,Ech. comm. Italie,Ech. comm. Suisse,Ech. comm. Allemagne-Belgique,Fioul - TAC,Fioul - Cogén.,Fioul - Autres,Gaz - TAC,Gaz - Cogén.,Gaz - CCG,Gaz - Autres,Hydraulique - Fil de l?eau + éclusée,Hydraulique - Lacs,Hydraulique - STEP turbinage,Bioénergies - Déchets,Bioénergies - Biomasse,Bioénergies - Biogaz,Stockage batterie,Déstockage batterie,Eolien terrestre,Eolien offshore
0,France,Données définitives,2024-01-01,00:00,55239.0,55000.0,54200.0,96.0,18.0,1975.0,39886.0,15557.0,0.0,6671.0,-2274.0,1211.0,-7824.0,20.0,-1447.0,-2636.0,-2235.0,-2214.0,2360.0,14.0,63.0,18.0,88.0,761.0,201.0,926.0,5001.0,1553.0,117.0,510.0,354.0,347.0,0.0,0.0,14976.0,581.0
1,France,Données définitives,2024-01-01,00:15,NaN,54300.0,53400.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,France,Données définitives,2024-01-01,00:30,55167.0,53600.0,52600.0,98.0,17.0,1926.0,38086.0,15467.0,0.0,6533.0,-2174.0,1217.0,-5890.0,20.0,-1447.0,-2636.0,-2235.0,-2214.0,2336.0,14.0,64.0,19.0,88.0,747.0,147.0,943.0,4928.0,1599.0,6.0,501.0,369.0,347.0,0.0,0.0,14888.0,579.0
3,France,Données définitives,2024-01-01,00:45,NaN,53200.0,51950.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,France,Données définitives,2024-01-01,01:00,53183.0,52800.0,51300.0,96.0,17.0,1987.0,37215.0,15411.0,0.0,6208.0,-2202.0,1225.0,-6659.0,21.0,-1431.0,-2636.0,-2102.0,-2280.0,1573.0,14.0,63.0,19.0,91.0,752.0,196.0,948.0,4909.0,1293.0,6.0,506.0,373.0,347.0,0.0,0.0,14830.0,581.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35132,France,Données définitives,2024-12-31,23:00,65437.0,64200.0,64300.0,92.0,17.0,2130.0,50923.0,10390.0,0.0,5377.0,-2014.0,1278.0,-2656.0,19.0,3009.0,-2900.0,-3589.0,-3200.0,3805.0,14.0,57.0,21.0,101.0,651.0,622.0,756.0,4503.0,718.0,155.0,548.0,386.0,344.0,0.0,0.0,9111.0,1279.0
35133,France,Données définitives,2024-12-31,23:15,NaN,64500.0,64550.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3009.0,-2900.0,-3589.0,-3200.0,3805.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35134,France,Données définitives,2024-12-31,23:30,65159.0,64800.0,64800.0,92.0,16.0,2121.0,51095.0,10520.0,0.0,5429.0,-1954.0,1288.0,-3358.0,19.0,3009.0,-2900.0,-3589.0,-3200.0,3805.0,14.0,57.0,21.0,101.0,651.0,613.0,756.0,4619.0,585.0,225.0,554.0,389.0,345.0,0.0,0.0,9183.0,1337.0
35135,France,Données définitives,2024-12-31,23:45,NaN,64400.0,64500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3009.0,-2900.0,-3589.0,-3200.0,3805.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35136,RTE ne pourra être tenu responsable de l'usage...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [181]:
df.dtypes

Périmètre                                   str
Nature                                      str
Date                                        str
Heures                                      str
Consommation                            float64
Prévision J-1                           float64
Prévision J                             float64
Fioul                                   float64
Charbon                                 float64
Gaz                                     float64
Nucléaire                               float64
Eolien                                  float64
Solaire                                 float64
Hydraulique                             float64
Pompage                                 float64
Bioénergies                             float64
Ech. physiques                          float64
Taux de Co2                             float64
Ech. comm. Angleterre                   float64
Ech. comm. Espagne                      float64
Ech. comm. Italie                       float64
Ech. comm. Suisse                       float64
Ech. comm. Allemagne-Belgique           float64
Fioul - TAC                             float64
Fioul - Cogén.                          float64
Fioul - Autres                          float64
Gaz - TAC                               float64
Gaz - Cogén.                            float64
Gaz - CCG                               float64
Gaz - Autres                            float64
Hydraulique - Fil de l?eau + éclusée    float64
Hydraulique - Lacs                      float64
Hydraulique - STEP turbinage            float64
Bioénergies - Déchets                   float64
Bioénergies - Biomasse                  float64
Bioénergies - Biogaz                    float64
 Stockage batterie                      float64
Déstockage batterie                     float64
Eolien terrestre                        float64
Eolien offshore                         float64
dtype: object

### Observation

Les colonnes de consommation et de production ne comportent des mesures que toutes les 30 minutes.

Les créneaux intermédiaires (00:15, 00:45, 01:15, etc.) présentent des valeurs manquantes pour ces variables.

À l'inverse, les colonnes de prévision (Prévision J-1 et Prévision J) sont renseignées toutes les 15 minutes.

### Hypothèse

Cette différence semble résulter d'une règle de publication des données et non d'un décalage ou d'une erreur d'importation.

### Action

Cette hypothèse sera confirmée par la documentation officielle de RTE et intégrée aux règles métier du projet.

In [179]:
(
  df.loc[df['Prévision J-1'].notnull()  , 'Heures']
  .value_counts()
  .sort_index()
)

Heures
00:00    366
00:15    366
00:30    366
00:45    366
01:00    366
01:15    366
01:30    366
01:45    366
02:00    366
02:15    366
02:30    366
02:45    366
03:00    366
03:15    366
03:30    366
03:45    366
04:00    366
04:15    366
04:30    366
04:45    366
05:00    366
05:15    366
05:30    366
05:45    366
06:00    366
06:15    366
06:30    366
06:45    366
07:00    366
07:15    366
07:30    366
07:45    366
08:00    366
08:15    366
08:30    366
08:45    366
09:00    366
09:15    366
09:30    366
09:45    366
10:00    366
10:15    366
10:30    366
10:45    366
11:00    366
11:15    366
11:30    366
11:45    366
12:00    366
12:15    366
12:30    366
12:45    366
13:00    366
13:15    366
13:30    366
13:45    366
14:00    366
14:15    366
14:30    366
14:45    366
15:00    366
15:15    366
15:30    366
15:45    366
16:00    366
16:15    366
16:30    366
16:45    366
17:00    366
17:15    366
17:30    366
17:45    366
18:00    366
18:15    366
18:30    366
18:45    366
19:00    366
19:15    366
19:30    366
19:45    366
20:00    366
20:15    366
20:30    366
20:45    366
21:00    366
21:15    366
21:30    366
21:45    366
22:00    366
22:15    366
22:30    366
22:45    366
23:00    366
23:15    366
23:30    366
23:45    366
Name: count, dtype: int64

In [166]:
df

,Périmètre,Nature,Date,Heures,Consommation,Prévision J-1,Prévision J,Fioul,Charbon,Gaz,Nucléaire,Eolien,Solaire,Hydraulique,Pompage,Bioénergies,Ech. physiques,Taux de Co2,Ech. comm. Angleterre,Ech. comm. Espagne,Ech. comm. Italie,Ech. comm. Suisse,Ech. comm. Allemagne-Belgique,Fioul - TAC,Fioul - Cogén.,Fioul - Autres,Gaz - TAC,Gaz - Cogén.,Gaz - CCG,Gaz - Autres,Hydraulique - Fil de l?eau + éclusée,Hydraulique - Lacs,Hydraulique - STEP turbinage,Bioénergies - Déchets,Bioénergies - Biomasse,Bioénergies - Biogaz,Stockage batterie,Déstockage batterie,Eolien terrestre,Eolien offshore
0,France,Données définitives,2024-01-01,00:00,55239.0,55000.0,54200.0,96.0,18.0,1975.0,39886.0,15557.0,0.0,6671.0,-2274.0,1211.0,-7824.0,20.0,-1447.0,-2636.0,-2235.0,-2214.0,2360.0,14.0,63.0,18.0,88.0,761.0,201.0,926.0,5001.0,1553.0,117.0,510.0,354.0,347.0,0.0,0.0,14976.0,581.0
1,France,Données définitives,2024-01-01,00:15,NaN,54300.0,53400.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,France,Données définitives,2024-01-01,00:30,55167.0,53600.0,52600.0,98.0,17.0,1926.0,38086.0,15467.0,0.0,6533.0,-2174.0,1217.0,-5890.0,20.0,-1447.0,-2636.0,-2235.0,-2214.0,2336.0,14.0,64.0,19.0,88.0,747.0,147.0,943.0,4928.0,1599.0,6.0,501.0,369.0,347.0,0.0,0.0,14888.0,579.0
3,France,Données définitives,2024-01-01,00:45,NaN,53200.0,51950.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,France,Données définitives,2024-01-01,01:00,53183.0,52800.0,51300.0,96.0,17.0,1987.0,37215.0,15411.0,0.0,6208.0,-2202.0,1225.0,-6659.0,21.0,-1431.0,-2636.0,-2102.0,-2280.0,1573.0,14.0,63.0,19.0,91.0,752.0,196.0,948.0,4909.0,1293.0,6.0,506.0,373.0,347.0,0.0,0.0,14830.0,581.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35132,France,Données définitives,2024-12-31,23:00,65437.0,64200.0,64300.0,92.0,17.0,2130.0,50923.0,10390.0,0.0,5377.0,-2014.0,1278.0,-2656.0,19.0,3009.0,-2900.0,-3589.0,-3200.0,3805.0,14.0,57.0,21.0,101.0,651.0,622.0,756.0,4503.0,718.0,155.0,548.0,386.0,344.0,0.0,0.0,9111.0,1279.0
35133,France,Données définitives,2024-12-31,23:15,NaN,64500.0,64550.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3009.0,-2900.0,-3589.0,-3200.0,3805.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35134,France,Données définitives,2024-12-31,23:30,65159.0,64800.0,64800.0,92.0,16.0,2121.0,51095.0,10520.0,0.0,5429.0,-1954.0,1288.0,-3358.0,19.0,3009.0,-2900.0,-3589.0,-3200.0,3805.0,14.0,57.0,21.0,101.0,651.0,613.0,756.0,4619.0,585.0,225.0,554.0,389.0,345.0,0.0,0.0,9183.0,1337.0
35135,France,Données définitives,2024-12-31,23:45,NaN,64400.0,64500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3009.0,-2900.0,-3589.0,-3200.0,3805.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35136,RTE ne pourra être tenu responsable de l'usage...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

0         True
1        False
2         True
3        False
4         True
         ...
35132     True
35133    False
35134     True
35135    False
35136    False
Name: Consommation, Length: 35137, dtype: bool